### ISSUE TITLE
Sandboxing and Mac App Store submission

### ISSUE THREAD

**Issue by gbasile** [bitstadium/QuincyKit#109]
Apple does not accept application with the proposed sandboxing exception. 
Have you planned to update the library so that the framework will be fully compatible for Mac submission?

Is it possible just to configure the support directory during the application launch? It would make possible to specify the Application support directory of the application.

**Comment by DerAndereAndi** [comment]
QuincyKit for Mac is not compatible with sandboxing and there are no settings to make it work.

The new HockeySDK-Mac for HockeyApp.net on the other hand is fully compatible with sandboxing on the Mac: https://github.com/bitstadium/HockeySDK-Mac

**Comment by gbasile** [comment]
Thanks, I'm gonna use that version!

**Comment by ishuo** [comment]
My app just got rejected by including of the temporary exception entitlements. I included the framework since in the Wiki it appears that QuincyKit is compatible with Mac App Store.

I think you should mention directly in project Wiki that the framework won't pass Mac App Store review. In this way many unnecessary rejections can be avoided.

**Comment by DerAndereAndi** [comment]
I explicitly added the text on every Mac wiki page and the main wiki page but never had to remove text. If there is a page left where you got the impression, please let me know.

**Comment by ishuo** [comment]
Thank you for the reply.

I didn't realize the problem by reading the main wiki (README.markdown). I think two points led to my misunderstanding.
1. There is the text
   
   > When using the client in a Sandbox, add the following temporary exception entitlement com.apple.security.temporary-exception.files.home-relative-path.read-only /Library/Logs.
   
   I thought it meant that by adding this temporary exception entitlement, I will get approved by Apple.
2. There is no explicit mention of **reject**, **not supported by Mac App Store** or something like that in the wiki. 
   They might sound bad, but would effectively communicate this problem.

**Comment by DerAndereAndi** [comment]
I don't think "reject" has to be in there, since rejection reasons may change, like it did. The SDK hasn't been updated a while and in the meantime Apple changed their rejection reasons which made the SDK not compatible any more. I don't want to run updating lots of sides every time this happens. It is not compatible, can't safe everyone. (Just check all the other Mac frameworks who suppose to do the same thing but won't work any more either)

Yeah, the readme. Well, I guess I'll do a commit to. But since this won't be a new version, it will only appear in the develop branch for now.

**Comment by ishuo** [comment]
I see. It's _verwirrend_ that Apple changes their rules without notifying people. Maybe you could make a warning like "there have been reports of compatibility issues with the Mac App Store"?

I don't think developer branch is a big problem. The readme of this branch is shown automatically when I open the project Github page. So at least I would notice the text.

I also don't understand why Apple includes the temporary exceptions entitlement, but rejects apps using it nonetheless :( .

Other than that, I like QuincyKit. It's a great framework for developers to obtain important infos. For example, I had a customer review "crashed within a minute in 10.8", though I and my friends have never experienced a crash in 10.8. I wish I had built QuincyKit in earlier. So... thank you and keep the great work!

**Comment by DerAndereAndi** [comment]
Readme changed. You can use our new HockeySDK-Mac SDK (https://github.com/bitstadium/HockeySDK-Mac) instead, which is App Store safe on the Mac, but it requires HockeyApp.net on the server side.

Thanks for the notice!

**Comment by ishuo** [comment]
Already baked HockeySDK in and submitted for review :)
