### ISSUE TITLE
Please post a build that includes the armv7s architecture

### ISSUE THREAD

**Issue by jongrall** [bitstadium/QuincyKit#113]
The new iPhone 5 requires builds with armv7s. The CrashReporter.framework dependency is only built for armv7 and armv6.

**Comment by ashtom** [comment]
We will provide an updated QuincyKit later this week. In the meantime, please have a look at http://support.hockeyapp.net/discussions/problems/2495#comment_18716493 and consider switching to our new SDK.

**Comment by andrei200287** [comment]
+1

**Comment by DerAndereAndi** [comment]
We highly encourage you to use the new HockeySDK frameworks when using HockeyApp. For using the open source server, we just updated the development branch and uploaded a new zip file into the download section with version 2.1.9 Beta 1 of the iOS client that support armv7 and armv7s.

**Comment by maddox** [comment]
So thats that? This won't ever happen? Does that mean this project is officially dead? Not implementing this def makes it useless. This should probably be reflected in the README.

**Comment by DerAndereAndi** [comment]
@maddox: please read again, we just updated the SDK! Check the develop branch for the changes or the download section for version 2.1.9 beta 1.

**Comment by maddox** [comment]
ohhhhh! I misread, thinking you meant you updated the Hockey SDK to support open source servers, and that we should move to that. 

Sorry about that! Thanks for handling this fast!

**Comment by Amiliar2012** [comment]
The RealKerni，Could you help me? , I need The CrashReporter.framework includes the armv6 ,armv7 and armv7s architecture . Thanks.
Best wishes!

**Comment by DerAndereAndi** [comment]
@Amiliar2012: I have not found a way to provide all 3 architectures in a properly working binary, since Xcode 4.5 doesn't not compile armv6 and Xcode 4.4.1 does not compile armv7s. If you really need armv6, then use the old version 2.1.8 and stick to Xcode 4.4.1. The iPhone 5 can safely run armv7 code just fine, there is no real need for most of the apps to have armv7s binary anyway.

**Comment by ahndee** [comment]
Couldn't you build an armv6 version with Xcode 4.4.1, an armv7/armv7s version with Xcode 4.5 and then use `lipo create …` to build a complete binary with support for all three architectures?

**Comment by DerAndereAndi** [comment]
@ahndee: we tried, but it doesn't work without problems. We just uploaded an armv6/armv7 only build which you can find in the downloads section. Again, if you need armv6 support, use that. There is really really no real need to provide an armv7s build, since the iPhone 5 can run any app with armv7 architecture just fine.

**Comment by Amiliar2012** [comment]
@TheRealKerni Is n't CrashReporter.framework that the kind of 3rd party framework Apple doesn't allow in the App Store? I want be sure,if i add the framework in my app, Apple will refuse?  Have you tried it before?

**Comment by DerAndereAndi** [comment]
@Amiliar2012: this framework is allowed. I am using it since 2009 (!!) in every app I do and it is being used in thousands of other apps. As the project description says, it is safe to be used in the AppStore for iOS.

**Comment by Amiliar2012** [comment]
@TheRealKerni ,Thanks!

**Comment by Amiliar2012** [comment]
@TheRealKerni  Does QuincyKit suport Mac app(cocoa app),does not it?

**Comment by DerAndereAndi** [comment]
@Amiliar2012: Yes, see https://github.com/TheRealKerni/QuincyKit/wiki/Mac-library-features and https://github.com/TheRealKerni/QuincyKit/tree/develop/demo/Mac

**Comment by Amiliar2012** [comment]
If i check sandboxing in cocoa project, QuincyKit will not catch the dictionary that is "/Users/xxx/Library/Logs/...", and the crashlog hasnot saved in sandboxing dictionary. Can you help me? I think it because limit me to access the user library, it only no limit in sandboxing library,but no crashLog in there.

**Comment by DerAndereAndi** [comment]
@Amiliar2012: Please create new ticket for issues that are not related to the original one.
