### ISSUE TITLE
Some problem in remote symbolication setup!

### ISSUE THREAD

**Issue by ghost** [bitstadium/QuincyKit#125]
Hi ,

I have implemented the server setup (remote symbolication)based on the documentation provided.
I downloaded a sample crash report and tried executing symbolicatecrash crashfilename.crash 
but the result i get is the same crash report which is not symbolized.

I have pasted the required .app.dSYM and .app files to the local folder containing the scripts also have run chmod +x symbolicatecrash.pl

Clearly I am missing something , can you help me find it out?

Please help.

**Comment by DerAndereAndi** [comment]
Hi,

either Spotlight doesn't find the symbols for the binary, the ones in the local path are not used because you did not use the option `.` at the end or the symbols don't match the required symbols by the crash report. Check this for hints: http://support.hockeyapp.net/kb/how-tos-faq/how-to-solve-symbolication-problems

You can also call the script via `symbolicatecrash -v` and your paramenters to get more information. But anyway, it's most like one of the above.

**Comment by ghost** [comment]
Thanks a lot..!! I was able to symbolicate successfully ..!!
