### ISSUE TITLE
Self-hosted crash reporting doesn't survive a 301 redirect

### ISSUE THREAD

**Issue by ngreenstein** [bitstadium/QuincyKit#139]
My crash reports weren't actually being submitted to my server; they were failing silently. I realized that a 301 redirect was the problem: it looks a request is made to the new URL, but the crash report itself isn't included. crash.php responded with `-3`, but there was no notification of this from Quincy.

It would be great if Quincy could handle 301 redirects, but it would also be helpful if it could warn of a problem instead of failing silently.

Thanks!

**Comment by DerAndereAndi** [comment]
The above commit should add support for redirects. Could you please verify?

If there is no network connection, the client will automatically retry, if you want to debug, set the `debugLogEnabled` property and check the console. I don't think it is a good idea to show any such warning to the end user, because there is usually nothing the user can do anyway.
