### ISSUE TITLE
Log grouping fails if applicationName includes a "for"

### ISSUE THREAD

**Issue by fkuehne** [bitstadium/QuincyKit#140]
We recently started to deploy QuincyKit in our own hosted environment and it works pretty well. However, the log grouping seems to be confused by the "for" in "VLC for iOS", which is both the application and the process name.

In turn, we get a bunch of "for" groups, depending on the number of for's in the stack trace. So, we have up to multiple hundred of logs grouped together solely because there are 2 internal calls in a row with absolutely no relations between the logs.

![screen shot 2014-01-21 at 13 25 56](https://f.cloud.github.com/assets/116994/1963284/98b65cae-8298-11e3-9676-3e96ba2575f4.png)

Could anyone provide guidance on this matter? That would be terrific!

**Comment by DerAndereAndi** [comment]
Hi Felix,

the grouping in general needs some work. The default grouping is using addresses in the stack traces, but due to ASLR (in iOS) that algorithm isn't working properly any more. (Besides the SDKs are also a bit outdated and I haven't found the time to work on both yet). The HockeyApp service doesn't have any of these problems, if you want to come back to our offering :)

I never heard about the problem you are mentioning though. Is this the grouping done when uploading the crash report or after symbolication? The name shouldn't ever be considered for grouping. Do you have an example of such a report?

Best,
Andreas

**Comment by fkuehne** [comment]
Hey Andreas,

Thanks a bunch for the rapid response. Regarding ASLR, I saw a few patches on some forks - I might check those more in detail. Regarding your HockeyApp offer, I need to discuss this with the team.. Thanks for repeating it!

It appears like the logs are grouped prior to symbolication. Here are 2 of them: http://cl.ly/2C0H392s0u3b I got a few more available on my server, if you are interested, also symbolicated :)

Thanks for your help!

Felix

**Comment by DerAndereAndi** [comment]
Thanks, I'll see when I can make some time for this, but can't promise anything. I assume there is a parser (regex) bug somewhere.

Btw, if you need another reason for HockeyApp, check this out: http://hockeyapp.net/releases/hockeycoach/ :) View crash reports with the actual source of the crashing app version inline!

**Comment by fkuehne** [comment]
Yep, checked the code yesterday and apparently the regex code assumes the caller not to contain any spaces. It's not like my fix succeeded though :)

**Comment by DerAndereAndi** [comment]
I just tested your logs with the latest code I pushed last night and it looks like those fixed it. In addition I just pushed another fix for parsing the binary images section of the crash reports to correctly handle app bundles with spaces in its name (spaces or other chars in there are never a good idea, the Apple symbolication tools, especially `otool`, don't like that and symbolication may not work properly).
