### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by kyvu** [bitstadium/QuincyKit#50]
I'm using the latest version and it crashes in the init method of QuincyKit at 
PLCrashReporter *crashReporter = [PLCrashReporter sharedReporter];

Also, I have to comment out this whole block of code for it to compile for some reason. Somehow it cannot find hasProcessInfo and processInfo.

```
if (report.hasProcessInfo) {
        /* Process Name */
        if (report.processInfo.processName != nil)
            processName = report.processInfo.processName;

        /* PID */
        processId = [[NSNumber numberWithUnsignedInteger: report.processInfo.processID] stringValue];

        /* Process Path */
        if (report.processInfo.processPath != nil)
            processPath = report.processInfo.processPath;

        /* Parent Process Name */
        if (report.processInfo.parentProcessName != nil)
            parentProcessName = report.processInfo.parentProcessName;

        /* Parent Process ID */
        parentProcessId = [[NSNumber numberWithUnsignedInteger: report.processInfo.parentProcessID] stringValue];
    }
```

**Comment by DerAndereAndi** [comment]
Hi,

since this is a PLCrashReporter issue, I suggest pointing that issue out at the projects issue tracker page instead: http://code.google.com/p/plcrashreporter/issues/list
- Andreas

P.S.: I guess Landon is reading here too. But this is not PLCrashReporter repo :)

**Comment by kyvu** [comment]
I got the whole .zip from hockeyapp.net to try out the service. I thought it points to here. Should I post it on hockeyapp.net forum?

**Comment by DerAndereAndi** [comment]
Hi,

I forwarded this issue to Landon Fuller, since he wrote the PLCrashReporter which you are experiencing issues with.

Nevertheless after reading your ticket like 10 times, I am slowly finding out what your are asking. So to better understand what you are actually doing, I got some more questions, which Landon probably would also require:

Did you download this repositories code yet and tried if the provided demo app works? If not, please do so and report back.

Did you follow the installation instructions and import the framework and set all required build settings? http://support.hockeyapp.net/kb/client-integration/crash-reporting-on-ios-quincykit

You say that the compiler doesn't go through without changing those lines of code. Could you post the error messages you get?

Andreas

**Comment by kyvu** [comment]
Hi,

Thanks for your quick reply. I actually follow that installation instruction. Here is the errors http://gyazo.com/be51180196249f204128a476b1cfeb3c it seems like it's not seeing PLCrashReporter or something. I double check that the framework is include properly and there is a link in the Framework Search Path to it. 

I just tried the Demo and it runs fine. Also, the Public ID is the app bundle id right?

**Comment by DerAndereAndi** [comment]
Please check that there is surely no older version of the PLCrashReporter framework in your source code lying around. Maybe compare the crashreporter.framework packages in your project and the one in the demo project.

The Public ID is the HockeyApp public ID you get assigned when creating an app there. It has nothing to do with the app bundle id. See the support page above, where this is documented.

**Comment by kyvu** [comment]
You were right. I have an old PLCrashReporter in my project from before so I guess it is using that instead of the new one. 

I got everything to work and so far I'm liking it. Thanks you for helping out.
