### ISSUE TITLE
Not getting dialog after crash application

### ISSUE THREAD

**Issue by idrish** [bitstadium/QuincyKit#53]
Hi,
Why my application is not giving me crash report dialog in next start up once application crashed? Its working fine in iOS4.2 but not above iOS4.3.2
Thanks

**Comment by DerAndereAndi** [comment]
Hi,

it is pretty hard, not to say impossible, to answer your question, since you did not provide any details on what you are doing.

Did you integrate the crashreporter framework correctly?
Did you integrate and initialize QuincyKit correctly?
Did you test with the debugger running?
Did you test in the simulator or on the device?
How do you test the crash?

Andreas

**Comment by idrish** [comment]
=>Yes all things are integrated properly as its working in iOS or simulator below 4.3.0.
=>I have tested on both simulator and device both but not working on iOS above 4.3.2
=>I have test called one method that was not exist actually so application crashed and another way was loading big pdf file and it cause memory issue.

**Comment by DerAndereAndi** [comment]
1. Memory problems are not crashes, in those cases the app will be killed by the system. You will not get a crash report if iOS kills your app.
2. In all our apps and to my knowledge there is no problem with the framework on iOS above 4.3.2
3. Does iOS create a crash report file? If yes, maybe you could debug it and set a breakpoint on the next startup after the app crashes. E.g. in BWQuincyManager.m line 159 and 912 to find out if a crash has been detected by PLCrashReporter or not.

**Comment by idrish** [comment]
I forgot to report crash file is not created.

**Comment by DerAndereAndi** [comment]
So you mean to say, iOS does not even create a crash report file? Why should PLCrashReporter create one then?

**Comment by idrish** [comment]
I debug little and I found that every time it doesn't found file (if ([_crashFiles count] == 0 && [fm fileExistsAtPath:_crashesDir]) {) return false every time.

**Comment by DerAndereAndi** [comment]
Ok, once more the question: does iOS create a crash report for those cases? Check with the organizer on your device.

**Comment by idrish** [comment]
Sometimes report generated but mostly its not generating report. Don't know why (For same crash statement or sentence)?

**Comment by DerAndereAndi** [comment]
If iOS doesn't generate a crash report, there is no reason PLCrashReporter will be able to create one. Since I don't know the code you are using to simulate a crash, I don't know what is happening. You might be doing something weird or wrong.

I suggest going to http://code.google.com/p/plcrashreporter/ and adding a ticket there. Show there which code you are actually using to simulate a crash, and the crash report iOS is writing. Explain all you know, which iOS version it is reliably working, on which it is sometimes or not working. Give them demo code and iOS crash reports.
