### ISSUE TITLE
Reachability code needed for iPhone client?

### ISSUE THREAD

**Issue by futuretap** [bitstadium/QuincyKit#6]
Looking shortly through the code, I noticed the iPhone lib listens for @"kNetworkReachabilityChangedNotification". This notification isn't sent by the system. I assume, you're depending on the Reachability sample code from Apple, right? And you're assuming, `-startNotifier` has been sent, right?
- Ortwin

**Comment by DerAndereAndi** [comment]
Right, I will add that to the readme. If it is not part of the application, all that happens is that on startup if there is not network connection the crash is not being sent out and so tried the next time the app starts. Otherwise it would send it as soon as a network connection is getting available while the app is running.

Andreas

**Comment by DerAndereAndi** [comment]
The framework is now listening to the `BWQuincyNetworkBecomeReachable` notification, that you can send if you integrate any reachability code to notify it that the device is now online. Then QuincyKit will send pending crash reports automatically to the server.
