### ISSUE TITLE
XMLReader - Bug when adding debug string data

### ISSUE THREAD

**Issue by steipete** [bitstadium/QuincyKit#9]
I just spent two hours tracking down a bug.

If custom data in crashReportDescription is added, and this data contains html-code like this

 ------------ Debug Information ------------<br>Application Version: 1.8.0 

then the crash is silently ignored.

the server returns following error:

parser error : Opening and ending tag mismatch: br line 0 and description in <b>/var/www/site/crashreporter/crash_v200.php</b> on line <b>119</b><br />
<br />
<b>Warning</b>:  XMLReader::read() [<a href='xmlreader.read'>xmlreader.read</a>]: d920f

this should be an easy fix on the server side.

**Comment by DerAndereAndi** [comment]
Hi, I just uploaded a patch for the server. This bug was present in early mac client versions, and theoretically also existed on the iOS, but that data should have never had any HTML code, since the user did not add anything there. I just commited a patch for iOS and a "patch" to make sure the data is parsed correctly, even if the clients makes a mistake.

**Comment by steipete** [comment]
I added the user (I have a function that queries some device data, that was formatted for email, thus the tags)

thanks!
